### ISSUE TITLE
MidiTrack.insertNote() should line 168 create a NoteOff instead of NoteOn

### ISSUE THREAD

**Issue by blinkmacalahan** [LeffelMania/android-midi-lib#10]
Seeing as how insertNote() is a shortcut for calling NoteOn and NoteOff shouldn't line 168 of MidiTrack.java create a NoteOff object?

**Comment by LeffelMania** [comment]
NoteOn with a velocity of 0 is equivalent to a NoteOff event; it's an optimization in the event stream so that a continuous stream of NoteOn events can be sent, resulting in fewer bytes in the stream.
