### ISSUE TITLE
How to calculate tick?

### ISSUE THREAD

**Issue by KenChoi1992** [LeffelMania/android-midi-lib#26]
```
NoteOff off = new NoteOff(tick, channel, pitch, 0);
```
When receive onSend(byte[] data, int offset, int count, long timestamp) event, we only know the event's timestamp, how to use timestamp to get tick? Timestamp is system's nano time

**Comment by zhangyufei49** [comment]
> ```
> NoteOff off = new NoteOff(tick, channel, pitch, 0);
> ```
> 
> When receive onSend(byte[] data, int offset, int count, long timestamp) event, we only know the event's timestamp, how to use timestamp to get tick? Timestamp is system's nano time

https://github.com/LeffelMania/android-midi-lib/blob/master/src/main/java/com/leff/midi/util/MidiUtil.java
