### ISSUE TITLE
choose Instrument

### ISSUE THREAD

**Issue by daStroob** [LeffelMania/android-midi-lib#4]
Hi Alex,

I'm working on a little project and your android-midi-lib is helping out a lot!

I think that there is an important feature missing though, which is the ability to specify a midi-instrument for a chanel. Or did I just miss the right method?

Anyways thanks a lot for your effort :)
Kind regards

**Comment by daStroob** [comment]
Sorry I found it. Didn't notice the ProgramChange class -.-
Thanks anyways

**Comment by strictlad** [comment]
Hi @daStroob ,
I'm facing up to specify a midi-instrument for a channel. I want to specify midi instrument and write to file. And I need your help how to use ProgramChange class to solve this problem as you mentioned above.
Thank you very much
